apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  # set to the number of nodes in the cluster
  replicas: 3

  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - api
              topologyKey: kubernetes.io/hostname

      containers:
        - name: api
          image: ghcr.io/bind-labs/backend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: api

---
apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    service.kubernetes.io/topology-mode: Auto
spec:
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
spec:
  rules:
    - host: api.bind.sh
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  number: 3000
