apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api.yaml
  - config.yaml
  - postgres.yaml
  - secret.yaml
  - service-account.yaml
namespace: backend
labels:
  - pairs:
      app.kubernetes.io/name: api
    includeSelectors: true
