apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  # set to the number of nodes in the cluster
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  # prefer geographically close replicas
  services:
    additional:
      - selectorType: r
        serviceTemplate:
          metadata:
            name: postgres-geo-r
            annotations:
              service.kubernetes.io/topology-mode: Auto

  bootstrap:
    initdb:
      database: bind
      owner: api
  managed:
    roles:
      - name: api
        ensure: present
        login: true
        passwordSecret:
          name: postgres-api-role

  monitoring:
    enablePodMonitor: true

  storage:
    size: 10Gi
  walStorage:
    size: 2Gi

  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: "2"
      memory: 2Gi
