apiVersion: v1
kind: ServiceAccount
metadata:
  name: api

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-leader-election
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-leader-election
subjects:
  - kind: ServiceAccount
    name: api
roleRef:
  kind: Role
  name: api-leader-election
  apiGroup: rbac.authorization.k8s.io
