name: Docker
on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Cache Nix
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build Docker Image
        run: |
          echo "Building image"
          docker load < $(nix build .#dockerImage --print-out-paths)

          echo "Tagging image"
          docker tag ghcr.io/bind-labs/backend:latest ghcr.io/bind-labs/backend:${{ github.sha }}

      - name: Push Docker Image as SHA
        run: |
          docker push ghcr.io/bind-labs/backend:${{ github.sha }}

      - name: Push Docker Image as Tag
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          docker tag ghcr.io/bind-labs/backend:latest ghcr.io/bind-labs/backend:${{ github.ref_name }}
          docker push ghcr.io/bind-labs/backend:${{ github.ref_name }}

      - name: Push Docker Image as latest
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push ghcr.io/bind-labs/backend:latest
