name: Deploy
on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

concurrency:
  group: docker-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Cache Nix
        uses: cachix/cachix-action@v14
        with:
          name: backend
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build Docker Image
        run: docker load < $(nix build .#dockerImage --print-out-paths)

      - name: Push Docker Image as SHA
        run: |
          docker tag ghcr.io/bind-labs/api:latest ghcr.io/bind-labs/api:${{ github.sha }}
          docker push ghcr.io/bind-labs/api:${{ github.sha }}

      - name: Push Docker Image as Tag
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          docker tag ghcr.io/bind-labs/api:latest ghcr.io/bind-labs/api:${{ github.ref_name }}
          docker push ghcr.io/bind-labs/api:${{ github.ref_name }}

      - name: Push Docker Image as latest
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push ghcr.io/bind-labs/api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set new image
        run: kustomize edit set image ghcr.io/bind-labs/api:latest=ghcr.io/bind-labs/api:${{ github.sha }}
        working-directory: k8s

      - name: Deploy to Kubernetes
        run: |
          mkdir ~/.kube
          echo -e "${{ secrets.KUBECONFIG }}" > ~/.kube/config

          kubectl apply -k k8s
          kubectl rollout restart deployment api
          kubectl rollout status deployment api --timeout=2m
